/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDownloadsRouteImport } from './routes/_authenticated/downloads'
import { Route as AuthenticatedEquipmentRouteImport } from './routes/_authenticated/equipment'
import { Route as AuthenticatedFavoritesRouteImport } from './routes/_authenticated/favorites'
import { Route as AuthenticatedImportRouteImport } from './routes/_authenticated/import'
import { Route as AuthenticatedManufacturersRouteImport } from './routes/_authenticated/manufacturers'
import { Route as AuthenticatedRecentRouteImport } from './routes/_authenticated/recent'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSourcesRouteImport } from './routes/_authenticated/sources'
import { Route as AuthenticatedAssembliesAssemblyIdRouteImport } from './routes/_authenticated/assemblies.$assemblyId'
import { Route as AuthenticatedAssetsIndexRouteImport } from './routes/_authenticated/assets.index'
import { Route as AuthenticatedCatalogsIndexRouteImport } from './routes/_authenticated/catalogs.index'
import { Route as AuthenticatedCatalogsCatalogIdRouteImport } from './routes/_authenticated/catalogs.$catalogId'
import { Route as AuthenticatedModelsModelIdRouteImport } from './routes/_authenticated/models.$modelId'
import { Route as AuthenticatedPartsIndexRouteImport } from './routes/_authenticated/parts.index'
import { Route as AuthenticatedPartsPartIdRouteImport } from './routes/_authenticated/parts.$partId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDownloadsRoute = AuthenticatedDownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEquipmentRoute = AuthenticatedEquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFavoritesRoute = AuthenticatedFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportRoute = AuthenticatedImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedManufacturersRoute =
  AuthenticatedManufacturersRouteImport.update({
    id: '/manufacturers',
    path: '/manufacturers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRecentRoute = AuthenticatedRecentRouteImport.update({
  id: '/recent',
  path: '/recent',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSourcesRoute = AuthenticatedSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssembliesAssemblyIdRoute =
  AuthenticatedAssembliesAssemblyIdRouteImport.update({
    id: '/assemblies/$assemblyId',
    path: '/assemblies/$assemblyId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssetsIndexRoute =
  AuthenticatedAssetsIndexRouteImport.update({
    id: '/assets/',
    path: '/assets/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCatalogsIndexRoute =
  AuthenticatedCatalogsIndexRouteImport.update({
    id: '/catalogs/',
    path: '/catalogs/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCatalogsCatalogIdRoute =
  AuthenticatedCatalogsCatalogIdRouteImport.update({
    id: '/catalogs/$catalogId',
    path: '/catalogs/$catalogId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedModelsModelIdRoute =
  AuthenticatedModelsModelIdRouteImport.update({
    id: '/models/$modelId',
    path: '/models/$modelId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPartsIndexRoute = AuthenticatedPartsIndexRouteImport.update({
  id: '/parts/',
  path: '/parts/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPartsPartIdRoute =
  AuthenticatedPartsPartIdRouteImport.update({
    id: '/parts/$partId',
    path: '/parts/$partId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/downloads': typeof AuthenticatedDownloadsRoute
  '/equipment': typeof AuthenticatedEquipmentRoute
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/import': typeof AuthenticatedImportRoute
  '/manufacturers': typeof AuthenticatedManufacturersRoute
  '/recent': typeof AuthenticatedRecentRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sources': typeof AuthenticatedSourcesRoute
  '/assemblies/$assemblyId': typeof AuthenticatedAssembliesAssemblyIdRoute
  '/catalogs/$catalogId': typeof AuthenticatedCatalogsCatalogIdRoute
  '/models/$modelId': typeof AuthenticatedModelsModelIdRoute
  '/parts/$partId': typeof AuthenticatedPartsPartIdRoute
  '/assets/': typeof AuthenticatedAssetsIndexRoute
  '/catalogs/': typeof AuthenticatedCatalogsIndexRoute
  '/parts/': typeof AuthenticatedPartsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/downloads': typeof AuthenticatedDownloadsRoute
  '/equipment': typeof AuthenticatedEquipmentRoute
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/import': typeof AuthenticatedImportRoute
  '/manufacturers': typeof AuthenticatedManufacturersRoute
  '/recent': typeof AuthenticatedRecentRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sources': typeof AuthenticatedSourcesRoute
  '/assemblies/$assemblyId': typeof AuthenticatedAssembliesAssemblyIdRoute
  '/catalogs/$catalogId': typeof AuthenticatedCatalogsCatalogIdRoute
  '/models/$modelId': typeof AuthenticatedModelsModelIdRoute
  '/parts/$partId': typeof AuthenticatedPartsPartIdRoute
  '/assets': typeof AuthenticatedAssetsIndexRoute
  '/catalogs': typeof AuthenticatedCatalogsIndexRoute
  '/parts': typeof AuthenticatedPartsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/downloads': typeof AuthenticatedDownloadsRoute
  '/_authenticated/equipment': typeof AuthenticatedEquipmentRoute
  '/_authenticated/favorites': typeof AuthenticatedFavoritesRoute
  '/_authenticated/import': typeof AuthenticatedImportRoute
  '/_authenticated/manufacturers': typeof AuthenticatedManufacturersRoute
  '/_authenticated/recent': typeof AuthenticatedRecentRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/sources': typeof AuthenticatedSourcesRoute
  '/_authenticated/assemblies/$assemblyId': typeof AuthenticatedAssembliesAssemblyIdRoute
  '/_authenticated/catalogs/$catalogId': typeof AuthenticatedCatalogsCatalogIdRoute
  '/_authenticated/models/$modelId': typeof AuthenticatedModelsModelIdRoute
  '/_authenticated/parts/$partId': typeof AuthenticatedPartsPartIdRoute
  '/_authenticated/assets/': typeof AuthenticatedAssetsIndexRoute
  '/_authenticated/catalogs/': typeof AuthenticatedCatalogsIndexRoute
  '/_authenticated/parts/': typeof AuthenticatedPartsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/dashboard'
    | '/downloads'
    | '/equipment'
    | '/favorites'
    | '/import'
    | '/manufacturers'
    | '/recent'
    | '/search'
    | '/settings'
    | '/sources'
    | '/assemblies/$assemblyId'
    | '/catalogs/$catalogId'
    | '/models/$modelId'
    | '/parts/$partId'
    | '/assets/'
    | '/catalogs/'
    | '/parts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/dashboard'
    | '/downloads'
    | '/equipment'
    | '/favorites'
    | '/import'
    | '/manufacturers'
    | '/recent'
    | '/search'
    | '/settings'
    | '/sources'
    | '/assemblies/$assemblyId'
    | '/catalogs/$catalogId'
    | '/models/$modelId'
    | '/parts/$partId'
    | '/assets'
    | '/catalogs'
    | '/parts'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/downloads'
    | '/_authenticated/equipment'
    | '/_authenticated/favorites'
    | '/_authenticated/import'
    | '/_authenticated/manufacturers'
    | '/_authenticated/recent'
    | '/_authenticated/search'
    | '/_authenticated/settings'
    | '/_authenticated/sources'
    | '/_authenticated/assemblies/$assemblyId'
    | '/_authenticated/catalogs/$catalogId'
    | '/_authenticated/models/$modelId'
    | '/_authenticated/parts/$partId'
    | '/_authenticated/assets/'
    | '/_authenticated/catalogs/'
    | '/_authenticated/parts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/downloads': {
      id: '/_authenticated/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof AuthenticatedDownloadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipment': {
      id: '/_authenticated/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof AuthenticatedEquipmentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/favorites': {
      id: '/_authenticated/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AuthenticatedFavoritesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/import': {
      id: '/_authenticated/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthenticatedImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manufacturers': {
      id: '/_authenticated/manufacturers'
      path: '/manufacturers'
      fullPath: '/manufacturers'
      preLoaderRoute: typeof AuthenticatedManufacturersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recent': {
      id: '/_authenticated/recent'
      path: '/recent'
      fullPath: '/recent'
      preLoaderRoute: typeof AuthenticatedRecentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sources': {
      id: '/_authenticated/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof AuthenticatedSourcesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assemblies/$assemblyId': {
      id: '/_authenticated/assemblies/$assemblyId'
      path: '/assemblies/$assemblyId'
      fullPath: '/assemblies/$assemblyId'
      preLoaderRoute: typeof AuthenticatedAssembliesAssemblyIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assets/': {
      id: '/_authenticated/assets/'
      path: '/assets'
      fullPath: '/assets/'
      preLoaderRoute: typeof AuthenticatedAssetsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catalogs/': {
      id: '/_authenticated/catalogs/'
      path: '/catalogs'
      fullPath: '/catalogs/'
      preLoaderRoute: typeof AuthenticatedCatalogsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catalogs/$catalogId': {
      id: '/_authenticated/catalogs/$catalogId'
      path: '/catalogs/$catalogId'
      fullPath: '/catalogs/$catalogId'
      preLoaderRoute: typeof AuthenticatedCatalogsCatalogIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/models/$modelId': {
      id: '/_authenticated/models/$modelId'
      path: '/models/$modelId'
      fullPath: '/models/$modelId'
      preLoaderRoute: typeof AuthenticatedModelsModelIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parts/': {
      id: '/_authenticated/parts/'
      path: '/parts'
      fullPath: '/parts/'
      preLoaderRoute: typeof AuthenticatedPartsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parts/$partId': {
      id: '/_authenticated/parts/$partId'
      path: '/parts/$partId'
      fullPath: '/parts/$partId'
      preLoaderRoute: typeof AuthenticatedPartsPartIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDownloadsRoute: typeof AuthenticatedDownloadsRoute
  AuthenticatedEquipmentRoute: typeof AuthenticatedEquipmentRoute
  AuthenticatedFavoritesRoute: typeof AuthenticatedFavoritesRoute
  AuthenticatedImportRoute: typeof AuthenticatedImportRoute
  AuthenticatedManufacturersRoute: typeof AuthenticatedManufacturersRoute
  AuthenticatedRecentRoute: typeof AuthenticatedRecentRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSourcesRoute: typeof AuthenticatedSourcesRoute
  AuthenticatedAssembliesAssemblyIdRoute: typeof AuthenticatedAssembliesAssemblyIdRoute
  AuthenticatedCatalogsCatalogIdRoute: typeof AuthenticatedCatalogsCatalogIdRoute
  AuthenticatedModelsModelIdRoute: typeof AuthenticatedModelsModelIdRoute
  AuthenticatedPartsPartIdRoute: typeof AuthenticatedPartsPartIdRoute
  AuthenticatedAssetsIndexRoute: typeof AuthenticatedAssetsIndexRoute
  AuthenticatedCatalogsIndexRoute: typeof AuthenticatedCatalogsIndexRoute
  AuthenticatedPartsIndexRoute: typeof AuthenticatedPartsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDownloadsRoute: AuthenticatedDownloadsRoute,
  AuthenticatedEquipmentRoute: AuthenticatedEquipmentRoute,
  AuthenticatedFavoritesRoute: AuthenticatedFavoritesRoute,
  AuthenticatedImportRoute: AuthenticatedImportRoute,
  AuthenticatedManufacturersRoute: AuthenticatedManufacturersRoute,
  AuthenticatedRecentRoute: AuthenticatedRecentRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSourcesRoute: AuthenticatedSourcesRoute,
  AuthenticatedAssembliesAssemblyIdRoute:
    AuthenticatedAssembliesAssemblyIdRoute,
  AuthenticatedCatalogsCatalogIdRoute: AuthenticatedCatalogsCatalogIdRoute,
  AuthenticatedModelsModelIdRoute: AuthenticatedModelsModelIdRoute,
  AuthenticatedPartsPartIdRoute: AuthenticatedPartsPartIdRoute,
  AuthenticatedAssetsIndexRoute: AuthenticatedAssetsIndexRoute,
  AuthenticatedCatalogsIndexRoute: AuthenticatedCatalogsIndexRoute,
  AuthenticatedPartsIndexRoute: AuthenticatedPartsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
